### ISSUE TITLE
Failed to fetch

### ISSUE THREAD

**Issue by Martyniuk** [uroslazarevic/repo-browser-server#4]
Faced with issue while log in, please see stack trace below

```
yarn run v1.22.19
$ nodemon ./index.js
[nodemon] 2.0.20
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node ./index.js`
Example app listening on port 4000
file:///testTasks/repo-browser-server/index.js:34
  const response = await fetch(OAUTH_ACCESS_TOKEN_URL, {
                   ^

ReferenceError: fetch is not defined
    at file:///testTasks/repo-browser-server/index.js:34:20
    at Layer.handle [as handle_request] (/testTasks/repo-browser-server/node_modules/express/lib/router/layer.js:95:5)
    at next (/testTasks/repo-browser-server/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/testTasks/repo-browser-server/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/testTasks/repo-browser-server/node_modules/express/lib/router/layer.js:95:5)
    at /testTasks/repo-browser-server/node_modules/express/lib/router/index.js:284:15
    at Function.process_params (/estTasks/repo-browser-server/node_modules/express/lib/router/index.js:346:12)
    at next (/testTasks/repo-browser-server/node_modules/express/lib/router/index.js:280:10)
    at urlencodedParser (/testTasks/repo-browser-server/node_modules/body-parser/lib/types/urlencoded.js:91:7)
    at Layer.handle [as handle_request] (/testTasks/repo-browser-server/node_modules/express/lib/router/layer.js:95:5)
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by uroslazarevic** [comment]
Hello @Martyniuk  👋 ,

Thanks for reporting this one, I forgot to pin node version which supports fetch feature.
Should be fixed with above [PR](https://github.com/uroslazarevic/repo-browser-server/pull/6).

**Comment by Martyniuk** [comment]
Great, thx for fast fix 💪
